### ISSUE TITLE
gist 13.0.0 Release Checklist

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1121]
Details are found in the [full documentation of the release process](https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists).

- [x] Create release branch (`release/X.x.x`).
- [x] Prepare release notes on the release branch.
- [x] Update `skos:historyNote` for new release.
- [x] Test logical consistency.
- [x] Contact @pwin to prepare the eBook and Widoco documentation from the OWL files on the release branch. This does not need to be completed before the release, but work can proceed while you proceed with the remaining steps.
- [x] Make any necessary modifications to the bundle configuration file.
- [x] Build the release package using `onto_tool` and inspect for correctness.
- [x] Make sure that the tables in the Markdown files are properly rendered in the HTML versions.
- [x] Ask 1-2 other ontologists to review the release package. Make any corrections needed and iterate through the build.
- [x] Email the release package to the developers.
- [x] Submit a PR from the release branch to `develop`.
- [x] Submit a PR from the release branch to `main`.
- [x] Add a new GitHub project for the next minor release if it does not already exist.
- [x] Add a new GitHub project for the next major release if it does not already exist.
- [x] Create an issue from this template and add it to each of the above two projects, if they do not already exist. Modify the title to include the version number.

Once the release has been posted to the website:
- [x] Test the release download.
- [x] Create a GitHub release.
- [x] Send notification of the release to JT along with text to update the [gist page on the SA website](https://www.semanticarts.com/gist/) and email text to send to gist Forum subscribers.
