### ISSUE TITLE
gist 14.0.0 Release Checklist

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1123]
See details in the [full documentation of the release process](https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists).

- [x] Create release branch (`release/14.0.0`).
- [x] Create a working branch off of this release branch for updates.
- [x] Prepare release notes.
- [x] Update `skos:historyNote` for new release.
- [x] Test logical consistency.
- [x] Contact @pwin to prepare the eBook (major version only) and Widoco documentation from the OWL files on the release branch. 
- [x] Make any necessary modifications to the bundle configuration file.
- [x] Build the release package using `onto_tool` and inspect for correctness.
- [x] Make sure that local links and tables in the Markdown files are properly rendered in the HTML versions. 
- [x] Ask one other ontologists to review the release package. Make any corrections needed and iterate through the build.
- [x] Create a GitHub release.
- [x] Email the release package to the developers.
- [x] Submit a PR from the release branch to `develop`.
- [x] Submit a PR from the release branch to `main`.
- [x] Add a new GitHub project for the next minor release if it does not already exist.
- [x] Add a new GitHub project for the next major release if it does not already exist.
- [x] Create issues from this template to add to each of the above two projects, if they do not already exist, modifying the title to include the version number.

Once the release has been posted to the website:
- [x] Test the release download.
- [x] Send text for email announcement and web page updates to responsible parties.
- [x] Test all links on the updated web page.
- [x] Follow up on eBook and Widoco documentation to ensure release after approximately one week.
