### ISSUE TITLE
Write queries for 10.0.0 migration script

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#505]
@sa-bpelakh 

Write queries to be executed by the 10.0.0 migration script for inclusion in the release package.

Involves deletes, inserts, and reports on what cannot be changed automatically. Details to be discussed with @sa-bpelakh.

## Tasks: List of v10 changes to be addressed:
- [x] #514
- [x] #515
- [ ] #557
- [ ] Migration: Refactored ordered collection model. Issues 112 & 540.
- [x] #558
- [x] Changes to and affecting gist:Person, as per issue 136: [JG] No action needed
- [x] Extended the range of fromPlace/toPlace to include gist:Address in addition to gist:Place. Issue 392. [JG] No action needed.
- [x] @sa-bpelakh Update release management confluence doc to reflect addition of migration scripts to release package.

**Comment by Jamie-SA** [comment]
I suggest using/editing the top comment of this issue to identify and track what needs to be done. I will start with a checkbox list of 2 simple tasks. We can use the discussion comments like this to identify and discuss what should be included.

I am also thinking we should create separate issues for each identified task and link to them in the task list.

**Comment by rjyounes** [comment]
Queries are straightforward - mostly local name changes.

**Comment by rjyounes** [comment]
Unassigning @daliadahleh because Jamie would like his team to get some practice writing SPARQL queries. The queries generally are of low complexity.

**Comment by rjyounes** [comment]
Desirable but not required for `10.0.0` release.

**Comment by rjyounes** [comment]
Adding @sa-bpelakh as an assignee so he can modify Confluence Release Management doc accordingly.
