### ISSUE TITLE
Add migration scripts for version 12

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#816]
@Jamie-SA I was thinking this would be a good issue for @coltonglasgow to work on, if he has the bandwidth. What do you think?

Here I am listing all issues that show up in the [Release Project](https://github.com/semanticarts/gist/projects/23#card-88882053)

- [x] [precedes/follows](https://github.com/semanticarts/gist/issues/551) - nothing to do (seems nothing was done or it was done previously) - part of removing inverses, so included in additional 
- [x] [Integrate new rdf-toolkit](https://github.com/semanticarts/gist/issues/774) - nothing to do
- [x] [Scope note adjusments on domainIncludes and rangeIncludes](https://github.com/semanticarts/gist/issues/736) - nothing to do
- [x] [Upgrade rdf-toolkit.jar to version 1.14.2 to suppress NamedIndividual assertions](https://github.com/semanticarts/gist/pull/788) - nothing to do
- [x] [pre-commit hook not running](https://github.com/semanticarts/gist/issues/794) - nothing to do
- [x] [Define unit of measure for percent](https://github.com/semanticarts/gist/pull/793) - nothing to do - goes with issue #785
- [x] [Add windows support to setup](https://github.com/semanticarts/gist/pull/798) - nothing to do
- [x] [Representing Percents](https://github.com/semanticarts/gist/issues/785) - Removed class `gist:Percentage`
> For each case where a gist:Precentage object with just a `gist:numericValue ${value}` exists, could we create a `gist:Magnitude` with  `gist:hasUnitOfMeasure gist:_percent` and `gist:numericValue ${value}`? For all other cases, we could warn the user that they are using a deprecated class and we couldn't automatically convert it.
- [x] [Adapt tools/setup.sh for Windows users](https://github.com/semanticarts/gist/issues/797) - nothing to do
- [x] [ Small modifications to bundle.yaml](https://github.com/semanticarts/gist/issues/754) - nothing to do
- [x] [ Update skos:definition of gist:nonConformingLabel](https://github.com/semanticarts/gist/pull/803) - nothing to do
- [x] [Reword definition of gist:nonConformingLabel](https://github.com/semanticarts/gist/issues/753) - nothing to do
- [x] [ Remove references to gistDeprecated from bundle.yaml](https://github.com/semanticarts/gist/pull/818) - nothing to do
- [x] [Issues relating to TimeZone and TimeZoneStandard](https://github.com/semanticarts/gist/issues/650) - report/warn if being used YES - also properties that were removed
- [x] [Remove Inverses](https://github.com/semanticarts/gist/pull/813) - report/warn about usage of removed properties. 
> Remove existing triples and add the ones with inverses, reversing the subject and object? In the ontology, you would need to change restrictions `owl:onProperty <deleted-property>  to `owl:onProperty [ owl:inverseOf <deleted-property> ]`. Same for domains and ranges.
- [x] [Fix Project and Task](https://github.com/semanticarts/gist/issues/760) - See below 
- [x] [Rework Event and Task Classes](https://github.com/semanticarts/gist/pull/777) - Report/warn using removed classes and update changed classes
- [x] [Update annotations on gist:isAllocatedBy](https://github.com/semanticarts/gist/pull/811) - nothing to do
- [x] [Added TimeInterval class](https://github.com/semanticarts/gist/pull/828) - nothing to do
- [x] [Remove distinction between Intergovernmental Organization Treaty Organization](https://github.com/semanticarts/gist/issues/766) - replace gist:TreatyOrganization with gist:IntergovernmentalOrganization
- [x] [Removed dateTime restrictions from Contingent Event ](https://github.com/semanticarts/gist/issues/776) - Nothing to do 
- [x] [Explicitly defined subClassOf](https://github.com/semanticarts/gist/issues/714) - nothing to do
- [x] [Broaden text definition of gist:isAllocatedBy](https://github.com/semanticarts/gist/issues/530) - nothing to do

In Review Tasks:
- [x] [Shouldn't gist use a PURL for its namespace IRI?](https://github.com/semanticarts/gist/issues/683)
  - [x] Change gist namespace from `https://ontologies.semanticarts.com/gist/` to `https://w3id.org/semanticarts/gist/` in instance data
  - [x] Change gist ontology IRIs in all ontology files from `https://ontologies.semanticarts.com/o/gist*` to `https://w3id.org/semanticarts/gist*`
  > Update gist prefix on all classes and properties (warn first)
  > Maybe break this out into separate queries for s, p, o, and g separated by semi colons

**Comment by rjyounes** [comment]
@Jamie-SA I made an initial pass through this and x'ed out some items, removed question marks, and added some TBDs which I have to look at later. 

For terms that are being removed, do you typically issue only a warning?

**Comment by Jamie-SA** [comment]
> For terms that are being removed, do you typically issue only a warning?

It depends. If there is no replacement then that is about all we can do. In the case of removing an inverse property we could suggest changes or actually update data (or provide the update query) to use the inverse instead.

**Comment by coltonglasgow** [comment]
> [ ] [Representing Percents](https://github.com/semanticarts/gist/issues/785) - Removed class `gist:Percentage`

@Jamie-SA, for each case where a `gist:Precentage` object with just a `gist:numericValue ${value}` exists, could we create a `gist:Magnitude` with ` gist:hasUnitOfMeasure gist:_percent` and `gist:numericValue ${value}`? For all other cases, we could warn the user that they are using a deprecated class and we couldn't automatically convert it.

**Comment by uscholdm** [comment]
> > [ ] [Representing Percents](https://github.com/semanticarts/gist/issues/785) - Removed class `gist:Percentage`
> 
> @Jamie-SA, for each case where a `gist:Precentage` object with just a `gist:numericValue ${value}` exists, could we create a `gist:Magnitude` with ` gist:hasUnitOfMeasure gist:_percent` and `gist:numericValue ${value}`? For all other cases, we could warn the user that they are using a deprecated class and we couldn't automatically convert it.

There never was a unit  gist:_percent, do we have one now with a conversion of .01 to base (gist:_each). I tihnk that is correct, but ti was never the way we did things. IF we do, then I think your suggestion make sense. It would be good to see sample triepls input and output to/from the script.

M.

**Comment by coltonglasgow** [comment]
@Jamie-SA, I have updated the task list above with action items. Please review the updated list with proposed migrations. Once approved, I will begin working on the migrations.

**Comment by uscholdm** [comment]
I would not be able to judge whether the scripts are good. Better to ask a developer
