### ISSUE TITLE
Add release note fixes

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#829]
- [x] Add release note for PR #828 
- [x] Fix release note for PR #793 - now a major change and a deletion rather than deprecation
- [x] Fix release note for PR #825 - this is a major change
- [x] Fix release note for PR #815 (conformance to format)

Also a few miscellaneous wording tweaks.
